apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealedsecret-backend-tokens.yaml

images:
  - name: ghcr.io/luisrodvilladaorg/app-luisops-backend
    newTag: 01decb4143bbb475edd090f4ee0c1b178df68ffe
  - name: ghcr.io/luisrodvilladaorg/app-luisops-frontend
    newTag: 01decb4143bbb475edd090f4ee0c1b178df68ffe
