apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealedsecret-backend-tokens.yaml

images:
  - name: ghcr.io/luisrodvilladaorg/app-luisops-backend
    newTag: 1c93dc27662c71aa79eebb9e3bac134955d01d3c
  - name: ghcr.io/luisrodvilladaorg/app-luisops-frontend
    newTag: 1c93dc27662c71aa79eebb9e3bac134955d01d3c
