apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealedsecret-backend-tokens.yaml

images:
  - name: ghcr.io/luisrodvilladaorg/app-luisops-backend
    newTag: 603d5d4192a56ca3c70fa00694beba380512eb31
  - name: ghcr.io/luisrodvilladaorg/app-luisops-frontend
    newTag: 603d5d4192a56ca3c70fa00694beba380512eb31
