apiVersion: v1
kind: Service
metadata:
  name: luisops-backend
  namespace: dashboard
  labels:
    app.kubernetes.io/name: luisops-backend
    app.kubernetes.io/part-of: luisops-dashboard
spec:
  type: ClusterIP
  selector:
    app: luisops-backend
  ports:
    - name: http
      port: 3100
      targetPort: 3100
